### ISSUE TITLE
How to save SMAC replays

### ISSUE THREAD

**Issue by bchiem42** [Replicable-MARL/MARLlib#104]
Hi ! 

Thanks a lot for the nice library that I am still discovering. 
I am currently trying to save SMAC replays after having successfully trained a MAPPO algorithm on the "3m" map. 
However, I can't figure out where the call to SMAC's "save_replay()" should be done when calling the render() method. 
Could you help me, and maybe add this point to the documentation as it may be useful for other users ? 

Thank you !

**Comment by Theohhhu** [comment]
Sure we can. While rendering procedures can differ across various environments, and that's why we haven't provided a one-size-fits-all solution. SMAC has a unique way of handling rendering by saving it as a replay and visualizing it using a real game engine. 

Will take some time to explore how to make rendering work in SMAC and back to you with more details soon.

**Comment by npnike10** [comment]
Hello @Theohhhu,
I am also interested in smac renders and wanted to know if there are any updates on this?
Thank you for your time!
