### ISSUE TITLE
How can I log the win rate on SMAC tasks?

### ISSUE THREAD

**Issue by ajlangley** [Replicable-MARL/MARLlib#135]
As title. How can I log the win rate from the evaluation during training?

**Comment by Theohhhu** [comment]
The concept of win rate is not universally applicable to all multi-agent tasks, which is why MARLlib does not include it as a default metric. However, if you wish to add a customized metric, there is an example in RLlib that demonstrates how to do so. You can find it [here](https://github.com/ray-project/ray/blob/ray-1.8.0/rllib/examples/custom_metrics_and_callbacks.py).

In a previous version of MARLlib, specifically in the SMAC implementation, we did incorporate win rate logging (now deprecated). You can refer to the code [here](https://github.com/Replicable-MARL/MARLlib/blob/mq_dev/SMAC/metric/smac_callback.py).
