### ISSUE TITLE
possibility of rendering like gymasium?

### ISSUE THREAD

**Issue by junwai7159** [Replicable-MARL/MARLlib#194]
as shown in the sample code provided, it seems like after mappo.fit I could only render the final training result using mappo.render, is it possible to render the env every n timesteps?

**Comment by Theohhhu** [comment]
Yes, rendering every 'n' episodes is possible. You can refer to [this example](https://github.com/ray-project/ray/blob/ray-1.8.0/rllib/examples/env_rendering_and_recording.py). Since MARLlib is built on RLlib, I cannot guarantee direct applicability. My suggestion is to verify whether the configuration is correctly set during training. For example, you may check [this line](https://github.com/Replicable-MARL/MARLlib/blob/0d73a4302fffa7a4584bafd0875ca996f636c1ad/marllib/marl/algos/run_cc.py#L176C25-L176C25) and confirm whether `render_env` is set to `true`.
